Algoritmo "viariáveis"
// Disciplina   : [Linguagem e Lógica de Programação] 
Var
   idade : inteiro
   altura : real
   nome : caractere
   casado : logico
   vet_uni : vetor [0..4] de real
   vet_bi : vetor [0..1,0..3] de inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   idade <- 18
   altura <- 1.86
   nome <- "Eduardo"
   casado <- falso
   vet_uni [2] <- 25
   vet_bi [0,2] <- 50
Fimalgoritmo